# -*- coding: utf-8 -*-
"""Sarah J (LD- 1787379388295).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aXbUxaOvp0_ruwFqV_Nh31YB3Neh70AZ

Student Placement Eligibility
Predict whether a student is likely to meet a placement eligibility criterion.

PROJECT ELEMENT	REQUIREMENT
Objective- Build a binary classification solution for the student placement eligibility use case.
Dataset	dataset_07_student_placement_eligibility.csv • 1,000 rows • 6 predictors + target
Target	target = 1 represents the positive/risk/event class; target = 0 represents the negative/non-event class.


Input variables	cgpa, attendance_pct, coding_score, projects_completed, internship_months, backlogs
Required algorithm	Logistic Regression. Establish a simple baseline where useful and compare only when technically justified.
Performance metrics	Accuracy, Precision, Recall, F1-score and ROC-AUC; include a confusion matrix.
"""

import zipfile
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report
)

"""These are all the packages and variables used in this program"""

df = pd.read_csv("dataset_07_student_placement_eligibility.csv")

"""Here, the data is being uploaded as a "CSV" file.
And the "pandas" package is being used to read the uploaded CSV file
"""

print("Shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nFirst 5 rows:")
print(df.head())

""""df.shape"- tells us the size of the dataset.
"df.columns"- shows the names of the columns.
"df.dtypes"- tells us what type of information each column contains.
"df.head()"- shows the first five rows of the dataset
"""

print("Missing values:")
print(df.isnull())
print(df.isnull().sum())

"""In this cell, the dataset is checked for any missing values.
As displayed in the output, there are no missing values in the dataset
"""

print("Number of duplicate rows:", df.duplicated().sum())

"""In this cell, the dataset is checked for any duplicaye values. As displayed in the output, there are no duplicate records."""

print(df['target'].value_counts())

"""The target variable contains 500 observations in class 0 and 500 observations in class 1. Therefore, the dataset is perfectly balanced, with each class representing 50% of the observations. This reduces the risk of the model being biased toward a majority class."""

print(df.describe())

"""It gives information such as:
count
mean
standard deviation
minimum
maximum
quartiles
"""

for column in df.columns:
    print(
        column,
        "\nMin =", df[column].min(),
        "\nMax =", df[column].max()
    )

"""This cell checks the minimum and maximum values of each variable."""

X = df.drop(columns=['target'])
y = df['target']

print("X shape:", X.shape)
print("y shape:", y.shape)

"""Here we separate the predictor variables from the target variable. X contains the six student-related features used for prediction, while y contains the target that the model needs to predict."""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

"""We divide the data into 80% training and 20% testing data. The training data is used to teach the model, while the testing data is kept unseen to evaluate its performance."""

model = Pipeline([
    ('scaler', StandardScaler()),
    ('logistic_regression', LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

model.fit(X_train, y_train)

"""The pipeline makes sure that the scaling is learned only from the training data, and then the same scaling is applied to the test data."""

y_pred = model.predict(X_test)

# Probability of class 1
y_prob = model.predict_proba(X_test)[:, 1]

"""fit() means: “Learn from these examples.”
Here it trains the modle using the traget features and their traget values
"""

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)

print("Accuracy :", round(accuracy, 4))
print("Precision:", round(precision, 4))
print("Recall   :", round(recall, 4))
print("F1-score :", round(f1, 4))
print("ROC-AUC  :", round(roc_auc, 4))

"""The first line generates the predicted classes for the test data. The second line obtains the predicted probability of class 1, which is used for probability-based evaluation."""

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

"""This cell evaluates the trained model using several performance measures."""

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=['Class 0', 'Class 1']
)

disp.plot()
plt.title("Confusion Matrix - Logistic Regression")
plt.show()

"""The confusion matrix shows exactly how the model's predictions compare with the actual classes."""

print(classification_report(y_test, y_pred))

"""This cell visualizes the confusion matrix so that the correct and incorrect predictions can be understood more easily."""

logistic_model = model.named_steps['logistic_regression']

coefficients = logistic_model.coef_[0]

coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': coefficients,
    'Odds_Ratio': np.exp(coefficients)
})

coef_df = coef_df.sort_values(
    by='Coefficient',
    ascending=False
)

print(coef_df)

"""Here there are number of test samples for each target class, giving a detailed view of model performance."""